### ISSUE TITLE
Tooltips stick around too eagerly

### ISSUE THREAD

**Issue by nadonomy** [element-hq/compound#235]
### Steps to reproduce

I don't have clear repro steps. But on calls, I notice often tooltips will display themselves long after I've interacted with the button (e.g. when clicking to mute/unmute).

@robintown can you think of any root cause, perhaps how we're handling button focus?

### Outcome

...

### Will you send logs?

No

**Comment by robintown** [comment]
We've rewritten our tooltip component and I really don't think I've seen this since.
