### ISSUE TITLE
Compound tooltips are inaccessible

### ISSUE THREAD

**Issue by t3chguy** [element-hq/compound#248]
They do not open via keyboard navigation, which means users of keyboard navigation without a screen reader or similar utility have no access to the content in the tooltip

**Comment by nadonomy** [comment]
For ref, documentation from Radix: https://www.radix-ui.com/primitives/docs/components/tooltip

Looks like it should support keyboard focus out of the box.

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/compound/assets/2403652/8aed9177-8399-49d3-a4e9-3f5921b0fe5b)

Their docs also imply we can't use their tooltips on interactive components which need those keys for themselves

**Comment by kerryarchibald** [comment]
Tooltips open on focus - according to [this](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html) I think we meet criteria without having another keybinding.
When applied to non-interactive elements they are inaccessible - [wrapping in a span](https://www.radix-ui.com/primitives/docs/components/tooltip#displaying-a-tooltip-from-a-disabled-button) is a suggested solution.

**Comment by t3chguy** [comment]
The wrapping in a span might cause an issue around keyboard focus though, if you activate a button which then gets disabled you wouldn't expect your focus to move, but as it would then get wrapped with a span your focus would be reset.

**Comment by t3chguy** [comment]
I believe this is resolved
