### ISSUE TITLE
Compound Tooltips are inaccessible

### ISSUE THREAD

**Issue by t3chguy** [element-hq/compound#295]
They only set an accessible name on hover/focus which isn't right:

![image](https://github.com/element-hq/compound/assets/2403652/7f892a29-9222-4372-8c54-a1b7a6a85a7c)

The way around it would be to specify `aria-label` on the child but then that'd result in the tooltip being read twice, once as the name/label and once for the description. 

This also makes it nigh impossible to write tests without using `data-testid` *everywhere*

**Comment by t3chguy** [comment]
@florianduros I believe you fixed this

**Comment by florianduros** [comment]
Yep

**Comment by florianduros** [comment]
(I don't have the rights to close it)
