### ISSUE TITLE
compound-web doesn't work on the server-side

### ISSUE THREAD

**Issue by sandhose** [element-hq/compound#314]
# Platform

- web

# Package version

- 3.0.1

# Description

Since https://github.com/element-hq/compound-web/pull/100, it's not possible to use compound web outside of a browser environment. This breaks server-side rendering, but also testing without a DOM, which we use in some tests in MAS.

This is because of the `getPlaform` util, which accesses the `navigator` global, which doesn't exist outside of a browser environment

**Comment by robintown** [comment]
I wasn't aware that server-side rendering is a use case compound-web was supporting, so we should also find a way to statically check for SSR compatibility once this is fixed

**Comment by Half-Shot** [comment]
We're also finding this on Next.JS builds for EMS / ESS. Seems to be an oddity with webpack:

```
 ⨯ ReferenceError: navigator is not defined
    at eval (webpack-internal:///../../node_modules/@vector-im/compound-web/dist/compound-web.js:727:21)
 ⨯ ReferenceError: navigator is not defined
    at eval (webpack-internal:///../../node_modules/@vector-im/compound-web/dist/compound-web.js:727:21)
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/home/will/git/matrix-hosted/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[7].oneOf[11].use[1]!/home/will/git/matrix-hosted/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[7].oneOf[11].use[2]!/home/will/git/matrix-hosted/node_modules/@vector-im/compound-web/dist/style.css': No serializer registered for W
```
