### ISSUE TITLE
compound-web doesn't tree-shake at all

### ISSUE THREAD

**Issue by sandhose** [element-hq/compound#318]
Currently, rendering a single `<Button>` from compound-web pulls approximately 350Kb of JS and 160Kb of CSS. This is because we ship compound as a single bundled file, which isn't marked as side-effect-free, which means that bundler can't tree-shake out unused code and unused `@radix-ui` dependencies.

This isn't necessarily a problem for Element Web as it consumes almost all of compound, but it adds unnecessary bloat to smaller projects like MAS.

**Comment by robintown** [comment]
On the subject of tree-shaking: we should also evaluate whether the project shouldn't follow https://jaydenseric.com/blog/optimal-javascript-module-design instead.
